{% set name = "handcalcs" %}
{% set version = "1.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/handcalcs-{{ version }}.tar.gz
  sha256: 97d807c65788e8b1d168714e2a0f9ee248cb32f3582674768516cd7fb4738b6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - innerscope >=0.2.0
    - more-itertools >=8.5.0
    - nbconvert >=6.0.0
    - pyparsing
    - python >=3.7

test:
  imports:
    - handcalcs
    - handcalcs.handcalcs_html
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/connorferster/handcalcs
  summary: Converts your Python calculation script into beautifully rendered Latex,
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
