{% set name = "handcalcs" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/handcalcs-{{ version }}.tar.gz
  sha256: 1a514968256eabbb57a46fd35d4d61613e64624b091e6964c61a6285663d7044

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - innerscope >=0.2.0
    - more-itertools >=8.5.0
    - nbconvert >=6.0.0
    - pyparsing
    - python >=3.7

test:
  imports:
    - handcalcs
    - handcalcs.handcalcs_html
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/connorferster/handcalcs
  summary: Converts your Python calculation script into beautifully rendered Latex,
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
